# Generated by Django 3.1.7 on 2021-03-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='libookapi.region')),
                ('time', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='libookapi.timeslice')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='libookapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='libookapi.regiongroup'),
        ),
    ]
