# Generated by Django 3.1.7 on 2021-03-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libookapi', '0002_auto_20210308_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_id',
            field=models.IntegerField(help_text='面部图像 ID', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_id',
            field=models.IntegerField(help_text='指纹 ID', null=True),
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(help_text='Token ID',
                                        primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Token', max_length=64)),
                ('expires_at', models.DateTimeField(help_text='Token 过期时间')),
                ('user', models.ForeignKey(help_text='对应用户',
                                           on_delete=django.db.models.deletion.CASCADE, to='libookapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(help_text='设备 ID',
                                        primary_key=True, serialize=False)),
                ('api_key', models.CharField(help_text='设备 API Key', max_length=64)),
                ('region', models.ForeignKey(help_text='设备所在区域',
                                             on_delete=django.db.models.deletion.CASCADE, to='libookapi.region')),
            ],
        ),
    ]
