# Generated by Django 3.1.7 on 2021-03-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libookapi', '0003_auto_20210313_0939'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timeslice',
            index=models.Index(fields=['from_time'],
                               name='libookapi_t_from_ti_72360b_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslice',
            index=models.Index(fields=['to_time'],
                               name='libookapi_t_to_time_693a70_idx'),
        ),
    ]
