# Generated by Django 3.1.7 on 2021-03-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libookapi', '0007_auto_20210314_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='sid',
        ),
    ]
