# Generated by Django 3.1.7 on 2021-03-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libookapi', '0009_auto_20210316_0818'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(
                fields=['user'], name='libookapi_r_user_id_1dfe83_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(
                fields=['region', 'time'], name='libookapi_r_region__512d99_idx'),
        ),
    ]
