# Generated by Django 3.1.7 on 2021-03-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libookapi', '0011_auto_20210325_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='region',
            field=models.ForeignKey(
                help_text='预定区域', on_delete=django.db.models.deletion.CASCADE, to='libookapi.region'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.ForeignKey(
                help_text='预定时间', on_delete=django.db.models.deletion.CASCADE, to='libookapi.timeslice'),
        ),
    ]
