# Generated by Django 3.1.7 on 2021-03-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libookapi', '0012_auto_20210325_1338'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='region',
            index=models.Index(
                fields=['group'], name='libookapi_r_group_i_ca7036_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(
                fields=['time'], name='libookapi_r_time_id_1ac949_idx'),
        ),
    ]
