# Generated by Django 3.1.7 on 2021-03-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libookapi', '0014_auto_20210327_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_present',
            field=models.BooleanField(default=False, help_text='是否成功入座'),
        ),
    ]
