name: Test
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Prepare
        run: |
          echo "POSTGRES_USER=sjtu-plus" > secrets/postgres-db.env
          echo "POSTGRES_PASSWORD=23333333" >> secrets/postgres-db.env
          touch secrets/influx-everything.env
          touch secrets/sjtu-plus.env
          touch secrets/grafana-private.ini
          touch secrets/grafana.ini
      - name: Init
        run: ./init.sh
      - name: Start Database
        run: docker-compose up -d postgres-db
      - name: Update
        run: ./update.sh
      - name: Test
        run: make test
      - name: Integration Test
        run: |
          docker-compose up -d --build caddy
          ./integration_test.sh