name: docker-compose
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Create necessary files
        run: |
          mkdir secrets
          touch secrets/libook.env
          touch secrets/postgres-db.env
      - name: Build
        run: docker-compose build
