name: Deploy dokku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Dokku
        uses: dokku/github-action@v1.0.1
        with:
            ssh_private_key: ${{ secrets.DOKKU_DEPLOY_KEY }}
            git_remote_url: 'ssh://dokku@libook.skyzh.dev:22/libook'
