name: Lint and Test frontend

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: install
      run: cd booklib && yarn
    - name: lint
      run: make lint.frontend
    - name: build
      run: make build.frontend
